### ISSUE TITLE
need a separate temp endpoint for free sample 

### ISSUE THREAD

**Issue by myidsan** [PerfDevTeam/perf_back#47]
/payment --> /samplepayment

Since we don't want the users for the 'free scent subscription' go through stripe (normal payment), we need to create a temporary endpoint to handle this.

**Comment by jameswhang** [comment]
Why is this endpoint needed

**Comment by myidsan** [comment]
We issued a FB ad for giving out free sample to people who subscribed to our page. We are aiming for max 200 samples (currently have 130ish people on the list), and we don't want them to go through the normal checkout process which includes typing in credit card number via stripe.

**Comment by jameswhang** [comment]
Yes. Why does that mean we need a separate endpoint on the backend side?

**Comment by myidsan** [comment]
We still want to save the info given by the user (shipping address, name, email etc) to our `payment` table. We thought it would be easier for us to have `/payment/freesample` endpoint added to handle this without changing the current `/payment`. Do you think having another controller method would be preferable?

**Comment by jameswhang** [comment]
So.... you're saying that your abstraction is fucked up because payment doesn't mean payment.

**Comment by jameswhang** [comment]
payment is supposed to do one thing - keep who paid how much for what. 

What you're saying is that you want to make an entirely separate endpoint for payments whose charge is equal to 0. 

1. You don't need another endpoint for that. If your request is charging for $0, you can opt out of creating a Stripe charge object. That way you only need only one endpoint. Don't duplicate code. 

2. You can't use payment to keep track of current status. That's not "payment" anymore. You need to call it something else like "order_status" or something like that instead of just calling it payment and dumping all the information that should be kept on a separate table or just called differently. I'm not suggesting one is better than the other, but either would be much better than abstracting the status of an order with the name "payment".

Before mindlessly writing code, think harder about the kind of abstraction you're making. Writing code is easy. Abstraction is hard.
